gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\Auth\RefreshToken\RefreshToken
    ttl: 2592000 # 20 sn & Default : 1 ay -> 2592000 sn
    ttl_update: true
    firewall: api
    token_parameter_name: refreshToken
    return_expiration: true
    return_expiration_parameter_name: refreshTokenExpiration
    logout_firewall: refresh_token_logout
