nelmio_api_doc:
    documentation:
        info:
            title: KNO API
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ] # Tüm endpointlerde varsayılan olarak uygulanacak
    areas: # to filter documented areas
        path_patterns:
            - ^/{_locale}/api(?!/doc$)|views # Accepts routes under /api except /api/doc
        disable_default_routes: true

