nelmio_api_doc:
    html_config:
        swagger_ui_config:
            tagsSorter: "alpha"
#            operationsSorter: "method"
#            operationsSorter: "alpha"
#            tagsSorter: >
#                function(a, b) {
#                  // Tag metadata'sına erişim
#                  var tags = window.ui.getSystem().specSelectors.specJson().get("tags").toJS();
#                  var getPriority = function(tagName) {
#                    var t = tags.find(t => t.name === tagName);
#                    return t && t['x-priority'] ? t['x-priority'] : 0;
#                  };
#                  // Önce priority'ye göre, sonra alfabetik sırala
#                  var diff = getPriority(b) - getPriority(a);
#                  return diff !== 0 ? diff : a.localeCompare(b);
#                }
    documentation:
        info:
            title: KNO API
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ] # Tüm endpointlerde varsayılan olarak uygulanacak
    areas: # to filter documented areas
        path_patterns:
            - ^/{_locale}/api(?!/doc$)|views # Accepts routes under /api except /api/doc
        disable_default_routes: true

