# Expose your documentation as JSON swagger compliant
app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.stoplight:
    path: /doc/stoplight
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.stoplight }

app.redocly:
    path: /doc/redocly
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.redocly }

app.swagger.json:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
