_security_logout:
    resource: security.route_loader.logout
    type: service


#api_login_check:
#    path: api/login_check


##api_token_invalidate:
##  path: /api/token/invalidate


#api_refresh_token:
#    path: api/token/refresh
