controller_full_auth_bundle_v1:
    resource: '../../Controller/Api'
    type: attribute

## TODO Burada herhangi bir locale eklemesi yapılmayacak çünkü bunlar bizim kendi içimizde oluşturduğumuz URL'ler değil. Zaten kabul etmedi
#api_login_check:
#    path: api/login_check
#
#
##api_token_invalidate:
##  path: /api/token/invalidate
#
## TODO Burada herhangi bir locale eklemesi yapılmayacak çünkü bunlar bizim kendi içimizde oluşturduğumuz URL'ler değil. Zaten kabul etmedi
#api_refresh_token:
#    path: api/token/refresh
