parameters:
    locale: 'tr'
    app_locales: tr
services:
    _defaults:
        public: false
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    #  custom_refresh_token_provider:
    #    class: SymfonyFullAuthBundle\Security\CustomRefreshTokenProvider
    #    arguments:
    #      $refreshTokenManager: '@gesdinet.jwtrefreshtoken.refresh_token_manager'
    #      $refreshTokenGenerator: '@gesdinet.jwtrefreshtoken.refresh_token_generator'

    custom_api_authenticator:
        class: SymfonyFullAuthBundle\Security\FullAuthApiBundleAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator
        #    arguments:
        #      $jwsProvider: '@lexik_jwt_authentication.jws_provider.lcobucci'
        #    calls:
        #      - setJwsProvider: ["lexik_jwt_authentication.jws_provider.lcobucci"]
        # arguments: ["lexik_jwt_authentication.jwt_manager","event_dispatcher","lexik_jwt_authentication.extractor.chain_extractor","","translator"]

    full_auth_bundle.event.jwt_created_listener:
        class: SymfonyFullAuthBundle\Security\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }



    SymfonyFullAuthBundle\:
        resource: "../../*"
        exclude:
            - '../../*/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


#    S\:
#        resource: "../../*"
#        exclude:
            - '../../*/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    #    lazy: true
    #
    #  SymfonyFullAuthBundle\Controller\FullAuthController:
    #    tags: [ 'controller.service_arguments' ]
    #    lazy: true

    #    web_user.example:
    #        class: Web\UserBundle\Example
    #        arguments: ["@service_id", "plain_value", "%parameter%"]
#  Ev\SymfonyCommandBundle\Command\:
#    resource: '../../Command/*'
#    exclude:
#      - '../../Command/GenerateBundleCommand/'
#      - '../../Command/CrudCommand/'
#    calls:
#      - setGenerator: [ '@?maker.generator' ]
#
##  Ev\SymfonyCommandBundle\Command\GenerateBundleCommand\GenerateBundleCommand:
##  Ev\SymfonyCommandBundle\BundleGenerator\Command\GenerateBundleCommand:
##    arguments: ["@service_container"]
##    calls:
##      - setGenerator: [ '@?maker.generator' ]
#
#  Ev\SymfonyCommandBundle\Command\CrudCommand\CrudCommand:
#    arguments:
#      - '@maker.doctrine_helper'
#      - '@maker.renderer.form_type_renderer'
#
#
#        #      resource: '../../Command/GenerateBundleCommand/GenerateBundleCommand.php'
#
#  Ev\SymfonyCommandBundle\Controller\:
#    resource: '../../Controller/*'
#    tags: ['controller.service_arguments']
#
#  Ev\SymfonyCommandBundle\BundleGenerator\Command\:
#    resource: '../../BundleGenerator/Command/*'
#    arguments: ["@service_container"]



