<?php

namespace App\Infrastructure\Form;

use Symfony\Component\Form\AbstractType;


class GenericForm extends AbstractType
{

//    public static function addToBuilder(FormBuilderInterface $builder, array $options = []): FormBuilderInterface
//    {
//
//        $builder->add("password", UserPasswordType::class,
//            $options
////            ["constraints" => [
////            new \SymfonyFullAuthBundle\Validator\PasswordStrength(),
////        ]]
//        );
//        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (PreSubmitEvent $event) {
//
//
//        });
//        return $builder;
//    }

//    public function buildForm(FormBuilderInterface $builder, array $options)
//    {
//        $builder->addEventListener(FormEvents::POST_SUBMIT, function (PostSubmitEvent $event) {
//            $this->postSubmitProcesses($event);
//
//        });
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
//    }

//    public function configureOptions(OptionsResolver $resolver): void
//    {
//
//
//    }


}
