controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

symfony_full_auth_bundle:
    resource: "@SymfonyFullAuthBundle/Resources/config/routing.yaml"
#
#app.swagger_ui:
#    path: /api/doc
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
