module_controllers:
    resource:
        path: ../src/Modules
        namespace: App\Modules
    type: attribute
    prefix: "/{_locale}/api"
    defaults:
        _locale: "tr"
    requirements:
        _locale: "tr|en"


sandbox_controllers:
    resource:
        path: ../src/Sandbox
        namespace: App\Sandbox
    type: attribute
    prefix: "/{_locale}/api/sandbox"
    defaults:
        _locale: "tr"
    requirements:
        _locale: "tr|en"







#base_controllers:
#    resource: "routes/modules.yaml"
#    prefix: "/{_locale}/api"
#    defaults:
#        _locale: "tr"
#    requirements:
#        _locale: "tr|en"
#
#
