controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: "/{_locale}/api"



symfony_full_auth_bundle:
    resource: "@SymfonyFullAuthBundle/Resources/config/routing.yaml"
    prefix: "/{_locale}/api"
    defaults:
        _locale: "tr"
    requirements:
        _locale: "tr|en"


