<?php

namespace App\Infrastructure\FormType\User;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserIdentifierFormType extends AbstractType
{
    const CHILD_NAME = "identifier";

//    public static function addToBuilder(FormBuilderInterface $builder, array $options = []): FormBuilderInterface
//    {
//        $builder->add("email", EmailType::class, $options);
//        return $builder;
//    }
//
//    public function buildForm(FormBuilderInterface $builder, array $options)
//    {
//        self::addToBuilder($builder,$options); // TODO: Change the autogenerated stub
//    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'property_path' => "email",
            "empty_data" => null,
            "attr" => ["autocomplete" => "new-password", "enterkeyhint" => "next", "tabindex" => 1],
            "label" => "Email",
//            "data_class" => User::class,
//            "constraints" => [
//              new Email()
//            ],
            "documentation" => [
                "type" => "string",
                "description" => "That is the login identifier of the user. Eg: email, username ",
            ]
        ]);
    }

    public function getParent(): string
    {
        return EmailType::class;
    }
}
